services:
  mongo:
    container_name: VENDA-MONGO-SERVER
    image: mongo:7-jammy
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - montadora_acme
  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    links:
      - mongo
    container_name: "mongo-express"
    ports:
      - 8090:8081
    networks:
      - montadora_acme
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: RABBITMQ
    ports:
      - "5672:5672"    
      - "15672:15672"  
    volumes:
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./config/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - montadora_acme
  postgres-doc:
    image: postgres
    container_name: POSTGRES-DOCUMENTO
    environment:
      - POSTGRES_PASSWORD=123456
    networks:
      - montadora_acme
  mariadb-security:
    image: mariadb
    container_name: MARIADB-SECURITY
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_USER=user-service
      - MARIADB_PASSWORD=123456
      - MARIADB_DATABASE=usuarios
    networks:
      - montadora_acme

  eureka-server:
    image: talesb/eureka
    container_name: EUREKA-SERVER
    ports:
      - "8761:8761"
    networks:
      - montadora_acme
  config-server:
    image: talesb/configserver
    container_name: CONFIG-SERVER
    environment:
      - GITHUB_TOKEN=
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - eureka-server
    networks:
      - montadora_acme
  montadora-service:
    image: talesb/montadora
    networks:
      - montadora_acme
    depends_on:
      - eureka-server
  revisao-service:
    image: talesb/revisao
    networks:
      - montadora_acme
    depends_on:
      - eureka-server
  carro-service:
    image: talesb/carro
    networks:
      - montadora_acme
    depends_on:
      - eureka-server
  security-service:
    image: talesb/security
    networks:
      - montadora_acme
    depends_on:
      - eureka-server
    ports:
      - "9997:9997"
  licenciamento-service:
    image: talesb/licenciamento
    networks:
      - montadora_acme
    depends_on:
      config-server:
        condition: service_healthy
  documento-service:
    image: talesb/documento
    networks:
      - montadora_acme
    depends_on:
      - eureka-server
      - rabbitmq
      - postgres-doc
  venda-service:
    image: talesb/venda
    networks:
      - montadora_acme
    depends_on:
      - eureka-server
      - mongo
  gateway-service:
    image: talesb/gateway
    networks:
      - montadora_acme
    depends_on:
      - eureka-server
    ports:
      - "9999:9999"
networks:
  montadora_acme:
    driver: bridge