version: '3'
services:
  mongo:
    container_name: VENDA-MONGO-SERVER
    image: mongo:7-jammy
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - carros
  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    links:
      - mongo
    container_name: "mongo-express"
    ports:
      - 8090:8081
    networks:
      - carros
networks:
  carros:
    external: true