server:
  port: 8080
spring:
  application:
    name: carro-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:carro
    username: sa
    password: ${SENHA_BANCO}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://EUREKA-SERVER:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      revisaoService:
        register-health-indicator: true
        minimum-number-of-calls: 1
        sliding-window-size: 3
        wait-duration-in-open-state:
          seconds: 1000