server:
  port: 8888
spring:
  profiles:
    active: docker
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Talesb/projeto-ms-noite-configrepo
          clone-on-start: true
          search-paths:
            - "config"
          username: Talesb
          password: ${GITHUB_TOKEN}

